### ISSUE TITLE
Bypass trusted domain check when using redirect API

### ISSUE THREAD

**Issue by surli** [xwikisas/identity-oauth#1]
XWiki 13.3RC1 and 12.10.7 introduced a security mechanism to avoid redirecting users to untrusted domains. Extension which uses this API can still bypass the check by setting `bypassDomainSecurityCheck` to true in the execution context before using the redirect API, to avoid problems if administrators don't properly set it up.

**Comment by polx** [comment]
done.

**Comment by surli** [comment]
Could you point out in which commit it has been done? just for archive purpose, I'm a bit surprised you didn't used the ticket number in the commit here.

**Comment by polx** [comment]
Indeed. Sorry for that. This was done [here](https://github.com/xwikisas/identity-oauth/commit/5ae645f514c93c52e817671af1a492f9dec661db#diff-b154183df8f3f295ad96ec361fa0d7541c24e2c39cd945f56039de40b113df67R191).
