### ISSUE TITLE
Profile saved at each login if avatar sync is enabled

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/identity-oauth#35]
**Prerequisites:**
1. Go to `Administer Wiki -> Other -> Azure AD` and check `User image` from `Permissions to request`
2. Have an Azure AD account with a avatar set (check [here](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/how-to-manage-user-profile-info)). Let's call it `User1`

**Steps to reproduce:**
1. Login with `User1` and check that he has the correct avatar added
2. Logout and login again
3. Check history for this profile

**Expected result:**
The avatar has not changed, so there are no modifications added to the profile

**Actual result:**
A new version was created with message `Identity OAuth login user updated.` even though no changes were done.
![image](https://github.com/xwikisas/identity-oauth/assets/22794181/b6479b8a-b791-437e-8e3a-3e577ad0b227)

This is not happening if there is no avatar set or the `User image` permission is not enabled.

**Comment by lucaa** [comment]
>  A new version was created with message Identity OAuth login user updated. even though no changes were done.

in addition to this, according to my tests, the attachment of the user profile _also_ gets a new version with an _identical file_,  which may quickly become expensive from a storage point of view (as attachments can be large).
